// MyFFT_Tables.c (Created by FFTDesigner - Version 3.56)

/******************************************************************************

COPYRIGHT.  This software is Copyright © 2011 RHDC Services Ltd.

        !  DO NOT EDIT THIS FILE AS IT MAY BE OVERWRITTEN BY
        THE DESIGNER RESULTING IN YOUR CHANGES BEING LOST  !

DISTRIBUTION.  This software may NOT be distributed to a third party without
prior written approval of the copyright holder. Please see the FFT Designer
End User Licence Agreement for details about distribution in object-code form.

DISCLAIMER.  This software is provided "AS IS", without express or implied
warranty.  In no event shall the copyright holder, author(s) or provider(s)
of this software be held liable for any damages arising from its use.

        FFTLength ................................ 128
        WindowType ............................... Kaiser
        WindowLoss (dB) .......................... 7,97
        Equivalent Noise Bandwidth ENBW (Bins) ... 1,81
        Inherent Power Gain ...................... 0,29
        Coherent Power Gain ...................... 0,16
        WindowAlpha .............................. 3
        Language ................................. MSP430 Extended C
        Algorithm ................................ Integer (16 Bit)
        Use Shift Division ....................... True
        Use Direct MPY32 Access .................. False

******************************************************************************/

#include "MyFFT_Tables.h"

// N/2 window coefficients in Q15 (signed fraction) format
const MyFFT_Workspace_t MyFFT_win[64]={20,37,59,88,124,170,227,295,376,473,586,717,867,1040,1236,1456,
1703,1979,2284,2620,2989,3392,3829,4302,4811,5357,5939,6559,7215,7907,8634,9395,10188,11013,11866,12745,
13648,14572,15514,16469,17436,18408,19384,20357,21324,22280,23221,24143,25039,25906,26740,27535,28288,
28994,29650,30251,30795,31278,31697,32050,32335,32550,32695,32767};

// N/2 real twiddle factors in Q15 (signed fraction) format
const MyFFT_Workspace_t MyFFT_twr[64]={32767,32727,32609,32412,32137,31785,31356,30851,30272,29621,28897,
28105,27244,26318,25329,24278,23169,22004,20787,19519,18204,16845,15446,14009,12539,11038,9511,7961,6392,
4807,3211,1607,0,-1607,-3211,-4807,-6392,-7961,-9511,-11038,-12539,-14009,-15446,-16845,-18204,-19519,
-20787,-22004,-23169,-24278,-25329,-26318,-27244,-28105,-28897,-29621,-30272,-30851,-31356,-31785,-32137,
-32412,-32609,-32727};

// N/2 imaginary twiddle factors in Q15 (signed fraction) format
const MyFFT_Workspace_t MyFFT_twi[64]={0,1607,3211,4807,6392,7961,9511,11038,12539,14009,15446,16845,
18204,19519,20787,22004,23169,24278,25329,26318,27244,28105,28897,29621,30272,30851,31356,31785,32137,
32412,32609,32727,32767,32727,32609,32412,32137,31785,31356,30851,30272,29621,28897,28105,27244,26318,
25329,24278,23169,22004,20787,19519,18204,16845,15446,14009,12539,11038,9511,7961,6392,4807,3211,1607};
