// MyFFT_TestHarness.c (Created by FFTDesigner - Version 3.56)

/******************************************************************************

COPYRIGHT.  This software is Copyright © 2011 RHDC Services Ltd.

        !  DO NOT EDIT THIS FILE AS IT MAY BE OVERWRITTEN BY
        THE DESIGNER RESULTING IN YOUR CHANGES BEING LOST  !

DISTRIBUTION.  This software may NOT be distributed to a third party without
prior written approval of the copyright holder. Please see the FFT Designer
End User Licence Agreement for details about distribution in object-code form.

DISCLAIMER.  This software is provided "AS IS", without express or implied
warranty.  In no event shall the copyright holder, author(s) or provider(s)
of this software be held liable for any damages arising from its use.

        FFTLength ................................ 128
        WindowType ............................... Kaiser
        WindowLoss (dB) .......................... 7,97
        Equivalent Noise Bandwidth ENBW (Bins) ... 1,81
        Inherent Power Gain ...................... 0,29
        Coherent Power Gain ...................... 0,16
        WindowAlpha .............................. 3
        Language ................................. MSP430 Extended C
        Algorithm ................................ Integer (16 Bit)
        Use Shift Division ....................... True
        Use Direct MPY32 Access .................. False

******************************************************************************/

#include "MyFFT_TestHarness.h"

// N FFT unwindowed input samples in Q15 (signed fraction) format
const MyFFT_Workspace_t MyFFT_SampledR[128]={0,32744,2475,-32557,-4935,32184,7367,-31627,-9758,30889,
12092,-29975,-14358,28890,16541,-27640,-18630,26232,20613,-24674,-22477,22976,24214,-21146,-25812,19195,
27263,-17134,-28558,14976,29689,-12732,-30652,10416,31439,-8040,-32046,5618,32471,-3164,-32710,692,32762,
1784,-32628,-4250,32306,6692,-31801,-9095,31113,11447,-30248,-13733,29210,15940,-28005,-18057,26641,20070,
-25124,-21969,23464,23742,-21669,-25380,19751,26873,-17720,-28212,15588,29390,-13367,-30400,11069,31237,
-8708,-31895,6298,32371,-3851,-32662,1383,32767,1094,-32684,-3564,32415,6013,-31960,-8429,31323,10796,
-30507,-13102,29517,15333,-28358,-17476,27038,19519,-25562,-21451,23941,23261,-22183,-24937,20298,26471,
-18298,-27854,16193,29078,-13995,-30136,11718,31021,-9373,-31730,6975,32257,-4537,-32600,2074,32756,402,
-32726,-2875};

const MyFFT_Workspace_t MyFFT_SampledI[128]={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

// N FFT windowed input samples in Q15 (signed fraction) format
const MyFFT_Workspace_t MyFFT_WindowedR[128]={0,36,4,-87,-18,166,51,-284,-111,445,216,-655,-379,916,623,
-1228,-968,1584,1436,-1972,-2050,2378,2829,-2776,-3789,3138,4941,-3429,-6288,3613,7822,-3650,-9530,3500,
11384,-3127,-13347,2498,15373,-1590,-17405,388,19380,1108,-21232,-2889,22893,4930,-24300,-7190,25389,
9618,-26112,-12151,26430,14715,-26318,-17235,25770,19630,-24792,-21822,23411,23741,-21668,-25323,19619,
26517,-17331,-27289,14879,27620,-12340,-27507,9794,26966,-7317,-26027,4979,24735,-2837,-23145,940,21323,
679,-19334,-2002,17248,3022,-15131,-3748,13046,4199,-11047,-4403,9177,4396,-7472,-4217,5953,3907,-4632,
-3506,3515,3053,-2592,-2581,1851,2116,-1275,-1682,841,1292,-527,-956,310,678,-167,-458,80,290,-31,-169,
7,87,0,-36,-1};

const MyFFT_Workspace_t MyFFT_WindowedI[128]={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

// N FFT output samples (FFT result) in Q15 (signed fraction) format
const MyFFT_Workspace_t MyFFT_TransformedR[128]={-6,-7,-7,-6,-3,-5,-6,-7,-2,-3,-4,-3,-4,-4,-5,-4,-1,-1,
-2,-3,0,-2,-3,-2,-2,0,-2,-1,-1,278,-2026,4193,-3350,939,-41,1,0,0,0,-1,-1,-2,-1,-1,-1,-1,-1,-2,0,0,-1,
0,0,-1,-1,0,-1,0,-1,-1,0,-1,-1,-1,0,1,1,2,1,1,0,1,0,1,2,1,0,2,1,2,1,-1,0,1,0,0,1,2,0,0,2,1,1,2,-40,941,
-3350,4197,-2023,281,2,2,0,1,-1,0,1,1,1,1,1,2,0,2,1,2,0,1,1,2,-1,0,1,1,0,3,1,3};

const MyFFT_Workspace_t MyFFT_TransformedI[128]={0,-5,-4,-4,-2,-2,-2,-2,-1,-2,-2,-2,-2,-2,-2,-1,0,-2,
-2,-2,0,-1,-2,-2,0,0,-1,-2,-2,-358,2440,-4815,3657,-979,40,-2,-1,-1,0,-1,-1,-1,-1,-1,0,-2,-1,-1,0,-1,
-2,-2,0,-1,-1,-2,0,-1,-2,-2,-1,-2,-2,-1,0,-1,0,0,0,0,0,0,-1,0,0,0,0,0,0,-1,0,0,-2,0,0,-1,0,0,0,0,1,0,
0,0,-42,977,-3657,4815,-2440,358,1,1,0,1,-1,-1,1,1,0,0,1,1,0,1,2,2,0,1,3,2,0,1,4,2,1,4,4,5};

void MyFFT_TestHarnessLoadComplex(const MyFFT_Workspace_t * table_pointer_r, const int * table_pointer_i)
{
	// Compare the complex result buffer from test vector table - Windowed
	MyFFT_Workspace_t * result_pointer_r = MyFFT_ResultR;
	MyFFT_Workspace_t * result_pointer_i = MyFFT_ResultI;
	
	int i=MyFFT_INPUT_LENGTH;
	do
	{
		*(result_pointer_r++) = *(table_pointer_r++); // copy the Real value
		*(result_pointer_i++) = *(table_pointer_i++); // copy the Imaginary value
	}
	while(--i);
}
void MyFFT_TestHarnessLoadSampled(void)
{
	// Compare the complex result buffer from test vector table - Sampled
	MyFFT_TestHarnessLoadComplex(MyFFT_SampledR, MyFFT_SampledI);
}
void MyFFT_TestHarnessLoadWindowed(void)
{
	// Compare the complex result buffer from test vector table - Windowed
	MyFFT_TestHarnessLoadComplex(MyFFT_WindowedR, MyFFT_WindowedI);
}
int MyFFT_TestHarnessCompareComplex(const MyFFT_Workspace_t * table_pointer_r, const MyFFT_Workspace_t * table_pointer_i)
{
	int ErrorCount=0; // return the number of errors found 
	// Compare the complex result buffer with test vector table - Transformed
	MyFFT_Workspace_t * result_pointer_r = MyFFT_ResultR;
	MyFFT_Workspace_t * result_pointer_i = MyFFT_ResultI;
	
	int i=MyFFT_INPUT_LENGTH;
	do
	{
		if(*(result_pointer_r++) != *(table_pointer_r++)) ErrorCount++; // check Real value
		if(*(result_pointer_i++) != *(table_pointer_i++)) ErrorCount++; // check Imag value
	}
	while(--i);
	return ErrorCount;
}
int MyFFT_TestHarnessCompareWindowed(void)
{
	return MyFFT_TestHarnessCompareComplex(MyFFT_WindowedR, MyFFT_WindowedI);
}
int MyFFT_TestHarnessCompareTransformed(void)
{
	return MyFFT_TestHarnessCompareComplex(MyFFT_TransformedR, MyFFT_TransformedI);
}
